#pragma kernel FindPositions

Texture2D<float4> _HeightMap;
SamplerState sampler_HeightMap;
RWStructuredBuffer<float3> _Vertices;

float _Dimension;
float _HeightMultiplier;

[numthreads(64, 1, 1)]
void FindPositions(uint3 id : SV_DispatchThreadID) {
    float3 vert = _Vertices[id.x];
    float2 uv = (vert.xz % _Dimension)/_Dimension;
    float4 displacement = _HeightMap.SampleLevel(sampler_HeightMap, uv, 0);

    _Vertices[id.x] = float3(vert.x, displacement.r * _HeightMultiplier, vert.z);
}